import { Opportunity } from "./client";

/** Bundled demo data — mirrors SportsBrain output when API is offline. */
export const DEMO_OPPORTUNITIES: Opportunity[] = [
  {
    match_id: "bund-001",
    match: "Bayern Munich vs Dortmund",
    sport: "soccer",
    league: "Bundesliga",
    kickoff_time: new Date(Date.now() + 36 * 3600000).toISOString(),
    recommended_market: null,
    decision: "Arbitrage",
    edge_score: 72.4,
    confidence: 90,
    grade: "A",
    risk_level: "Medium",
    pass_reason: "",
    fair_odds: null,
    market_odds: null,
    expected_value: null,
    reasoning_summary:
      "Cross-bookmaker arbitrage detected with 2.14% margin. Stake allocation covers all outcomes profitably. Execute fast before line correction.",
    team_strength_analysis: "Bayern: True strength 93.0/100 (Full strength)\nDortmund: True strength 86.0/100 (Full strength)",
    coach_analysis: "Coach data unavailable for this fixture.",
    form_analysis: "Form data unavailable.",
    xg_analysis: "xG data unavailable for this fixture.",
    market_intelligence: "Bookmaker spread — Home: 0.17 | Away: 0.60.\nPricing discrepancy detected — potential value or arb window.",
    context_factors: ["Der Klassiker — high liquidity"],
    monte_carlo_results: { home_win: 0.48, draw: 0.26, away_win: 0.26, over_25: 0.62, btts: 0.58 },
    multi_agent_council_summary: {
      consensus: "Council detects potential edge on Bayern Munich vs Dortmund. 1 specialists flag opportunity.",
      confidence: 78,
      edge_detected: true,
    },
    red_team_concerns: { approved: true, concerns: [], summary: "APPROVED — Edge survives red team scrutiny with manageable concerns." },
    explainability: { golden_rule: "Data → Probability → Value → Risk → Decision" },
    philosophy: "Kraitos does not pick winners. Kraitos finds edges.",
  },
  {
    match_id: "efl-001",
    match: "Bolton Wanderers vs Peterborough",
    sport: "soccer",
    league: "EFL League One",
    kickoff_time: new Date(Date.now() + 72 * 3600000).toISOString(),
    recommended_market: "Match Winner",
    decision: "Value Bet",
    edge_score: 68.2,
    confidence: 74,
    grade: "A",
    risk_level: "Medium",
    pass_reason: "",
    fair_odds: 2.15,
    market_odds: 2.80,
    expected_value: 8.4,
    reasoning_summary:
      "Kraitos model estimates 55% true probability vs market implied 36% on Bolton Wanderers Win. Expected value +8.4%. Edge score 68/100.",
    team_strength_analysis: "Bolton: True strength 62.0/100 (Full strength)\nPeterborough: True strength 52.5/100 (Injuries: Fry, Morton)",
    coach_analysis: "Coach data unavailable for this fixture.",
    form_analysis: "Form data unavailable.",
    xg_analysis: "Bolton: xG 1.8 | xGA 1.2 — Underrated\nPeterborough: xG 1.1 | xGA 1.9 — Overrated",
    market_intelligence: "Soft book home price vs market — possible value on home.",
    context_factors: ["Promotion race — Bolton high motivation", "Peterborough fixture congestion"],
    monte_carlo_results: { home_win: 0.52, draw: 0.24, away_win: 0.24, over_25: 0.55, btts: 0.48 },
    multi_agent_council_summary: { consensus: "Council detects potential edge.", confidence: 72, edge_detected: true },
    red_team_concerns: { approved: true, concerns: ["Lower league data quality"], summary: "APPROVED — Edge survives red team scrutiny." },
    explainability: {},
    philosophy: "Kraitos does not pick winners. Kraitos finds edges.",
  },
  {
    match_id: "epl-001",
    match: "Arsenal vs Liverpool",
    sport: "soccer",
    league: "Premier League",
    kickoff_time: new Date(Date.now() + 26 * 3600000).toISOString(),
    recommended_market: "Match Winner",
    decision: "Watchlist",
    edge_score: 42,
    confidence: 58,
    grade: "C",
    risk_level: "Medium",
    pass_reason: "",
    fair_odds: 2.35,
    market_odds: 2.45,
    expected_value: 2.1,
    reasoning_summary: "Watchlist — marginal signal detected. Monitor for line movement.",
    team_strength_analysis: "Arsenal: True strength 79.4/100 (Injuries: Saka, Timber)\nLiverpool: True strength 86.6/100",
    coach_analysis: "Arteta (Home): Possession pressing. Venue overperformance: +12%.\nSlot (Away): High press transitions. Venue overperformance: +15%.",
    form_analysis: "Arsenal: L5=WWDWW — Improving\nLiverpool: L5=WWWLW — Stable elite",
    xg_analysis: "Arsenal: xG 2.1 — Fair\nLiverpool: xG 2.4 — Slight underperformance vs xG",
    market_intelligence: "Sharp money activity: Moderate. Steam move direction: Neutral.",
    context_factors: ["Title race implications", "Arsenal 4 days rest", "Historical rivalry — elevated variance"],
    monte_carlo_results: { home_win: 0.38, draw: 0.28, away_win: 0.34, over_25: 0.71, btts: 0.65 },
    multi_agent_council_summary: { consensus: "Council consensus: marginal edge.", confidence: 65, edge_detected: false },
    red_team_concerns: { approved: false, concerns: ["Rivalry variance", "Marginal EV"], summary: "REJECT — Weak opportunity." },
    explainability: {},
    philosophy: "Kraitos does not pick winners. Kraitos finds edges.",
  },
  {
    match_id: "lal-001",
    match: "Getafe vs Osasuna",
    sport: "soccer",
    league: "La Liga",
    kickoff_time: new Date(Date.now() + 18 * 3600000).toISOString(),
    recommended_market: null,
    decision: "Pass",
    edge_score: 25,
    confidence: 35,
    grade: "PASS",
    risk_level: "Low",
    pass_reason: "PASS — No Edge Detected.",
    fair_odds: null,
    market_odds: null,
    expected_value: null,
    reasoning_summary:
      "PASS — No Edge Detected. After analysing team strength, form, xG, market intelligence, Monte Carlo simulations, and council consensus, no edge clear enough to risk capital.",
    team_strength_analysis: "Getafe: True strength 65.0/100\nOsasuna: True strength 66.0/100\nClosely matched on true strength.",
    coach_analysis: "Coach data unavailable.",
    form_analysis: "Form data unavailable.",
    xg_analysis: "xG data unavailable.",
    market_intelligence: "Market efficiently priced.",
    context_factors: ["Low event match — efficient market pricing"],
    monte_carlo_results: { home_win: 0.35, draw: 0.32, away_win: 0.33, over_25: 0.38, btts: 0.42 },
    multi_agent_council_summary: { consensus: "No actionable edge — capital preservation recommended.", confidence: 40, edge_detected: false },
    red_team_concerns: { approved: false, concerns: ["No quantitative edge"], summary: "REJECT — Insufficient evidence." },
    explainability: {},
    philosophy: "Kraitos does not pick winners. Kraitos finds edges.",
  },
  {
    match_id: "nba-001",
    match: "Los Angeles Lakers vs Boston Celtics",
    sport: "basketball",
    league: "NBA",
    kickoff_time: new Date(Date.now() + 48 * 3600000).toISOString(),
    recommended_market: "Match Winner",
    decision: "Value Bet",
    edge_score: 61.5,
    confidence: 70,
    grade: "B",
    risk_level: "Medium",
    pass_reason: "",
    fair_odds: 2.05,
    market_odds: 2.20,
    expected_value: 5.8,
    reasoning_summary: "Kraitos model estimates 49% vs market 45% on Lakers Win. Celtics form sustainable but Lakers home court undervalued with rest advantage.",
    team_strength_analysis: "Lakers: 73.9/100 (Injuries: Davis)\nCeltics: 92.5/100 (Full strength)",
    coach_analysis: "Coach data unavailable.",
    form_analysis: "Lakers: Volatile — False winning streak risk\nCeltics: Elite sustainable form",
    xg_analysis: "xG data unavailable.",
    market_intelligence: "Public money bias: Home favourite overload.",
    context_factors: ["Back-to-back for Lakers", "Playoff seeding implications"],
    monte_carlo_results: { home_win: 0.42, draw: 0, away_win: 0.58, over_25: 0.5, btts: 0 },
    multi_agent_council_summary: { consensus: "Potential edge detected.", confidence: 68, edge_detected: true },
    red_team_concerns: { approved: true, concerns: ["Lakers form misleading"], summary: "APPROVED with concerns." },
    explainability: {},
    philosophy: "Kraitos does not pick winners. Kraitos finds edges.",
  },
];
