"""Professional Strategy Playbook — strategies that fit market stories, not indicators."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

StrategyId = Literal[
    "trend_continuation",
    "pullback_to_value",
    "breakout",
    "false_breakout",
    "liquidity_sweep_reversal",
    "liquidity_sweep_continuation",
    "range_mean_reversion",
    "session_breakout",
    "opening_range_breakout",
    "volatility_expansion",
    "momentum_scalp",
    "trend_exhaustion",
    "supply_demand_reaction",
    "vwap_reversion",
    "smc_liquidity",
    "ict_liquidity",
    "wyckoff_accumulation",
    "wyckoff_distribution",
]


@dataclass(frozen=True)
class StrategyDefinition:
    """One professional playbook with conditions, models, and failure signs."""

    strategy_id: StrategyId
    name: str
    works_when: tuple[str, ...]
    fails_when: tuple[str, ...]
    best_timeframe: str
    best_session: str
    best_volatility: str
    entry_model: str
    stop_model: str
    target_model: str
    scaling_rules: str
    failure_signs: tuple[str, ...]
    base_expectancy: float
    confidence_adjustment: str

    def to_dict(self) -> dict:
        return {
            "strategy_id": self.strategy_id,
            "name": self.name,
            "works_when": list(self.works_when),
            "fails_when": list(self.fails_when),
            "best_timeframe": self.best_timeframe,
            "best_session": self.best_session,
            "best_volatility": self.best_volatility,
            "entry_model": self.entry_model,
            "stop_model": self.stop_model,
            "target_model": self.target_model,
            "scaling_rules": self.scaling_rules,
            "failure_signs": list(self.failure_signs),
            "base_expectancy": self.base_expectancy,
            "confidence_adjustment": self.confidence_adjustment,
        }


PROFESSIONAL_STRATEGY_PLAYBOOK: tuple[StrategyDefinition, ...] = (
    StrategyDefinition(
        strategy_id="trend_continuation",
        name="Trend Continuation",
        works_when=("clear directional trend", "pullback to value", "continuation probability high"),
        fails_when=("confirmed reversal", "range compression without breakout prep"),
        best_timeframe="H1/M15",
        best_session="london_ny_overlap",
        best_volatility="normal_to_expanding",
        entry_model="Enter on pullback reclaim of structure / VWAP",
        stop_model="Beyond last swing invalidation",
        target_model="Prior liquidity pool or measured move",
        scaling_rules="Scale 50% at 1R, trail runner on structure",
        failure_signs=("lower high after buy entry", "acceptance fails at value"),
        base_expectancy=0.62,
        confidence_adjustment="+5 when trend quality > 70",
    ),
    StrategyDefinition(
        strategy_id="pullback_to_value",
        name="Pullback to Value",
        works_when=("trend intact", "retracement to premium/discount", "reaction at value"),
        fails_when=("trend exhaustion", "deep retracement > 78%"),
        best_timeframe="M15/M5",
        best_session="london",
        best_volatility="compressed_to_normal",
        entry_model="Limit at value zone with reaction confirmation",
        stop_model="Beyond invalidation swing",
        target_model="Trend continuation liquidity",
        scaling_rules="Probe first, add on acceptance",
        failure_signs=("no reaction at value", "immediate acceptance against thesis"),
        base_expectancy=0.58,
        confidence_adjustment="+8 when location quality > 80",
    ),
    StrategyDefinition(
        strategy_id="breakout",
        name="Breakout",
        works_when=("compression", "breakout preparation score high", "volume expansion"),
        fails_when=("false breakout history", "thin session"),
        best_timeframe="M15/H1",
        best_session="london_ny_overlap",
        best_volatility="expanding",
        entry_model="Enter on close through level with retest hold",
        stop_model="Inside broken structure",
        target_model="Measured move / next liquidity",
        scaling_rules="Full on acceptance, reduce if retest fails",
        failure_signs=("immediate rejection back inside range", "weak volume on break"),
        base_expectancy=0.55,
        confidence_adjustment="+10 when breakout_risk > 65",
    ),
    StrategyDefinition(
        strategy_id="false_breakout",
        name="False Breakout / Fakeout",
        works_when=("failed breakout at range edge", "reversal pressure rising"),
        fails_when=("genuine trend breakout with acceptance", "news expansion"),
        best_timeframe="M5/M15",
        best_session="london",
        best_volatility="compressed",
        entry_model="Fade failed breakout back into range",
        stop_model="Beyond fakeout extreme",
        target_model="Range midpoint / opposite edge",
        scaling_rules="Single entry, tight management",
        failure_signs=("sustained acceptance outside range", "volume confirms break"),
        base_expectancy=0.54,
        confidence_adjustment="+12 when failed breakout evidence present",
    ),
    StrategyDefinition(
        strategy_id="liquidity_sweep_reversal",
        name="Liquidity Sweep Reversal",
        works_when=("stop hunt below support or above resistance", "reclaim", "trapped participants"),
        fails_when=("no reclaim", "trend continuation after shallow sweep"),
        best_timeframe="M5/M15",
        best_session="london",
        best_volatility="normal",
        entry_model="Enter after sweep and reclaim of key level",
        stop_model="Beyond sweep extreme",
        target_model="Opposite liquidity pool",
        scaling_rules="Probe until acceptance confirms",
        failure_signs=("no reclaim", "immediate continuation through level"),
        base_expectancy=0.61,
        confidence_adjustment="+15 when liquidity sweep detected",
    ),
    StrategyDefinition(
        strategy_id="liquidity_sweep_continuation",
        name="Liquidity Sweep Continuation",
        works_when=("sweep in trend direction", "institutional continuation narrative"),
        fails_when=("counter-trend sweep without structure", "reversal phase dominant"),
        best_timeframe="M15/H1",
        best_session="london_ny_overlap",
        best_volatility="expanding",
        entry_model="Enter pullback after directional sweep",
        stop_model="Beyond sweep low/high",
        target_model="Next structural liquidity",
        scaling_rules="Scale on trend acceptance",
        failure_signs=("opposite side gains control post-sweep",),
        base_expectancy=0.63,
        confidence_adjustment="+10 when sweep aligns with HTF trend",
    ),
    StrategyDefinition(
        strategy_id="range_mean_reversion",
        name="Range Mean Reversion",
        works_when=("horizontal range", "price at range edge", "low breakout risk"),
        fails_when=("breakout in progress", "trending regime"),
        best_timeframe="M15",
        best_session="asia",
        best_volatility="compressed",
        entry_model="Fade range boundary with rejection",
        stop_model="Beyond range edge",
        target_model="Equilibrium / opposite edge",
        scaling_rules="Reduce size near equilibrium",
        failure_signs=("acceptance outside range", "breakout preparation rising"),
        base_expectancy=0.52,
        confidence_adjustment="+8 when range quality > 65",
    ),
    StrategyDefinition(
        strategy_id="session_breakout",
        name="Session Breakout",
        works_when=("session open drive", "prior session range defined"),
        fails_when=("already extended", "low liquidity session"),
        best_timeframe="M5/M15",
        best_session="london_open",
        best_volatility="expanding",
        entry_model="Break of session range with momentum",
        stop_model="Inside session range",
        target_model="Session extension target",
        scaling_rules="Quick partial at 1R",
        failure_signs=("fade back into range",),
        base_expectancy=0.53,
        confidence_adjustment="+6 during london open",
    ),
    StrategyDefinition(
        strategy_id="opening_range_breakout",
        name="Opening Range Breakout",
        works_when=("defined opening range", "NY/London open", "volume pickup"),
        fails_when=("wide opening range", "already trend-extended"),
        best_timeframe="M5",
        best_session="new_york",
        best_volatility="expanding",
        entry_model="Break of OR high/low with retest",
        stop_model="Opposite side of opening range",
        target_model="1x OR width extension",
        scaling_rules="Standard size, fast management",
        failure_signs=("false break of OR",),
        base_expectancy=0.51,
        confidence_adjustment="+5 at NY open",
    ),
    StrategyDefinition(
        strategy_id="volatility_expansion",
        name="Volatility Expansion",
        works_when=("compression ending", "ATR expanding", "directional bias"),
        fails_when=("still compressing", "no directional clue"),
        best_timeframe="M15",
        best_session="london_ny_overlap",
        best_volatility="expanding",
        entry_model="Enter on expansion candle with structure",
        stop_model="Below expansion origin",
        target_model="Liquidity at extension target",
        scaling_rules="Trail aggressively after 1.5R",
        failure_signs=("expansion fails immediately", "reversion to mean"),
        base_expectancy=0.56,
        confidence_adjustment="+7 when compression_probability was high",
    ),
    StrategyDefinition(
        strategy_id="momentum_scalp",
        name="Momentum Scalp",
        works_when=("micro trend aligned", "high scalp quality", "session liquid"),
        fails_when=("spread wide", "low expectancy micro", "conflicting HTF"),
        best_timeframe="M1/M5",
        best_session="london_ny_overlap",
        best_volatility="normal",
        entry_model="Micro momentum entry with tight stop",
        stop_model="Beyond micro structure",
        target_model="Quick liquidity pocket",
        scaling_rules="Single scalp, no runner unless quality > 75",
        failure_signs=("momentum stalls", "micro reversal"),
        base_expectancy=0.48,
        confidence_adjustment="+10 when scalp_expectancy > 60",
    ),
    StrategyDefinition(
        strategy_id="trend_exhaustion",
        name="Trend Exhaustion Fade",
        works_when=("exhaustion phase", "reversal probability > continuation"),
        fails_when=("healthy trend continuation", "shallow pullback only"),
        best_timeframe="H1/M15",
        best_session="any",
        best_volatility="high",
        entry_model="Fade into exhaustion with confirmation",
        stop_model="Beyond exhaustion extreme",
        target_model="Mean reversion / prior value",
        scaling_rules="Reduced size only",
        failure_signs=("trend resumes immediately",),
        base_expectancy=0.50,
        confidence_adjustment="+8 when reversal_probability > 0.65",
    ),
    StrategyDefinition(
        strategy_id="supply_demand_reaction",
        name="Supply & Demand Reaction",
        works_when=("fresh zone", "first touch", "rejection wick"),
        fails_when=("zone already mitigated", "acceptance through zone"),
        best_timeframe="M15/H1",
        best_session="london",
        best_volatility="normal",
        entry_model="Reaction at institutional zone",
        stop_model="Beyond zone invalidation",
        target_model="Next opposing zone",
        scaling_rules="Probe at zone, add on rejection confirmation",
        failure_signs=("no rejection", "zone breaks"),
        base_expectancy=0.57,
        confidence_adjustment="+10 when location quality > 85",
    ),
    StrategyDefinition(
        strategy_id="vwap_reversion",
        name="VWAP Reversion",
        works_when=("overextended from VWAP", "mean reversion probability high"),
        fails_when=("strong trend riding VWAP", "acceptance away from value"),
        best_timeframe="M5/M15",
        best_session="new_york",
        best_volatility="normal",
        entry_model="Fade stretch back toward VWAP",
        stop_model="Beyond extension extreme",
        target_model="VWAP touch",
        scaling_rules="Quick partial at VWAP",
        failure_signs=("trend continues away from VWAP",),
        base_expectancy=0.49,
        confidence_adjustment="+6 when mean_reversion_score > 70",
    ),
    StrategyDefinition(
        strategy_id="smc_liquidity",
        name="Smart Money Concepts — Liquidity",
        works_when=("BOS/CHoCH", "liquidity pool mapped", "inducement sweep"),
        fails_when=("no structure shift", "random noise"),
        best_timeframe="M15/H1",
        best_session="london",
        best_volatility="normal",
        entry_model="Enter after inducement and structure shift",
        stop_model="Beyond inducement level",
        target_model="Draw on liquidity / imbalance fill",
        scaling_rules="Scale at internal liquidity",
        failure_signs=("structure shift fails",),
        base_expectancy=0.59,
        confidence_adjustment="+8 with clear BOS/CHoCH",
    ),
    StrategyDefinition(
        strategy_id="ict_liquidity",
        name="ICT Liquidity Concepts",
        works_when=("judas swing", "kill zone timing", "displacement"),
        fails_when=("outside kill zone", "no displacement"),
        best_timeframe="M5/M15",
        best_session="london_ny_overlap",
        best_volatility="expanding",
        entry_model="Kill zone entry after displacement",
        stop_model="Beyond judas swing",
        target_model="Next draw on liquidity",
        scaling_rules="Standard with session awareness",
        failure_signs=("no displacement", "wrong session"),
        base_expectancy=0.55,
        confidence_adjustment="+7 in kill zone",
    ),
    StrategyDefinition(
        strategy_id="wyckoff_accumulation",
        name="Wyckoff Accumulation",
        works_when=("range after downtrend", "spring", "sign of strength"),
        fails_when=("markdown continuing", "no spring"),
        best_timeframe="H1/H4",
        best_session="any",
        best_volatility="compressed_to_normal",
        entry_model="Enter after spring and SOS",
        stop_model="Below spring low",
        target_model="Range top / markup target",
        scaling_rules="Build position on confirmation",
        failure_signs=("lower low after spring",),
        base_expectancy=0.58,
        confidence_adjustment="+10 with accumulation evidence",
    ),
    StrategyDefinition(
        strategy_id="wyckoff_distribution",
        name="Wyckoff Distribution",
        works_when=("range after uptrend", "upthrust", "sign of weakness"),
        fails_when=("markup continuing", "no upthrust"),
        best_timeframe="H1/H4",
        best_session="any",
        best_volatility="compressed_to_normal",
        entry_model="Enter after upthrust and SOW",
        stop_model="Above upthrust high",
        target_model="Range bottom / markdown target",
        scaling_rules="Build on confirmation",
        failure_signs=("higher high after upthrust",),
        base_expectancy=0.57,
        confidence_adjustment="+10 with distribution evidence",
    ),
)


def playbook_by_id(strategy_id: str) -> StrategyDefinition | None:
    for strategy in PROFESSIONAL_STRATEGY_PLAYBOOK:
        if strategy.strategy_id == strategy_id:
            return strategy
    return None
